### ISSUE TITLE
Freya in Ulduar

### ISSUE THREAD

**Issue by Tauriella** [scriptdev2/scriptdev2#173] opened 2015-07-20 15:52 UTC
If you attack Boss Freya makes it a Loop text message

SAY_AGGRO_IRON                      = -1603018,

**Comment by Tauriella** [comment] 2015-08-16 12:49
Any News ?

**Comment by xfurry** [comment] 2015-08-16 13:06
Not yet. Need to spend some time with this to investigate.

**Comment by ghost** [comment] 2015-09-11 12:16
``` diff
commit 96871a6df3af774c9910404a33351c9cf9a8cfe7
Date:   Fri Sep 11 17:13:00 2015 +0600

    Freya Elders script.

diff --git a/scripts/northrend/ulduar/ulduar/boss_freya.cpp b/scripts/northrend/ulduar/ulduar/boss_freya.cpp
index a13d3e4..022cc11 100644
--- a/scripts/northrend/ulduar/ulduar/boss_freya.cpp
+++ b/scripts/northrend/ulduar/ulduar/boss_freya.cpp
@@ -17,7 +17,7 @@
 /* ScriptData
 SDName: boss_freya
 SD%Complete: 95%
-SDComment: Elders and some of the Nature Allies handled in ACID. Script might require some minor improvements.
+SDComment: Nature Allies handled in ACID. Script might require some minor improvements.
 SDCategory: Ulduar
 EndScriptData */

@@ -151,7 +151,29 @@ enum
     SPELL_LIFEBINDERS_GIFT_VISUAL       = 62579,
     SPELL_AUTO_GROW                     = 62559,                // cast by npcs 33228 and 33215
     SPELL_PHEROMONES                    = 62619,
-
+    
+    // elder stonebark spells
+    SPELL_GROUND_TREMOR_N               = 62325,
+    SPELL_GROUND_TREMOR_H               = 62932,
+    SPELL_PETRIFIED_BARK_N              = 62337,
+    SPELL_PETRIFIED_BARK_H              = 62933,
+    SPELL_FISTS_OF_STONE                = 62344,
+    
+    // elder ironbranch spells
+    SPELL_IMPALE_N                      = 62310,
+    SPELL_IMPALE_H                      = 62928,
+    SPELL_THORN_SWARM_N                 = 62285,
+    SPELL_THORN_SWARM_H                 = 62931,
+    SPELL_IRON_ROOTS_N                  = 62275,
+    SPELL_IRON_ROOTS_H                  = 62929,
+    
+    // elder brightleaf
+    SPELL_SOLAR_FLARE_N                 = 62240,
+    SPELL_SOLAR_FLARE_H                 = 62920,
+    SPELL_UNSTABLE_SUN_BEAM_N           = 62921,
+    SPELL_UNSTABLE_SUN_BEAM_H           = 64088,
+    SPELL_BRIGHTLEAF_FLUX               = 62262,
+    
     // allies of nature summons
     NPC_DETONATING_LASHER               = 32918,                // has auras 64481 and 28819
     NPC_ANCIENT_CONSERVATOR             = 33203,
@@ -1008,6 +1030,186 @@ CreatureAI* GetAI_npc_healthy_spore(Creature* pCreature)
     return new npc_healthy_sporeAI(pCreature);
 }

+/*######
+## boss_freya_elders
+######*/
+
+struct boss_freya_eldersAI : public ScriptedAI
+{
+    boss_freya_eldersAI(Creature* pCreature) : ScriptedAI(pCreature)
+    {
+        m_pInstance = (instance_ulduar*)pCreature->GetInstanceData();
+        m_bIsRegularMode = pCreature->GetMap()->IsRegularDifficulty();
+        Reset();
+    }
+
+    instance_ulduar* m_pInstance;
+    bool m_bIsRegularMode;
+
+    uint32 m_uiGroundTremorTimer;
+    uint32 m_uiPetrifiedBarkTimer;
+    uint32 m_uiFistStoneTimer;    
+    uint32 m_uiImpaleTimer;
+    uint32 m_uiThornSwarmTimer;
+    uint32 m_uiIronRoorsTimer;  
+    uint32 m_uiSolarFlareTimer;
+    uint32 m_uiUnstableSunBeamTimer;
+    uint32 m_uiBrightleafFluxTimer;
+
+    void Reset() override
+    {
+        // Stonebark Timers
+        m_uiGroundTremorTimer       = 0;
+        m_uiPetrifiedBarkTimer      = 0;
+        m_uiFistStoneTimer          = 0;
+        
+        // Ironbranch Timers
+        m_uiImpaleTimer             = 0;
+        m_uiThornSwarmTimer         = 0;
+        m_uiIronRoorsTimer          = 0;
+        
+        // Brightleaf Timers
+        m_uiSolarFlareTimer         = 0;
+        m_uiUnstableSunBeamTimer    = 0;
+        m_uiBrightleafFluxTimer     = 0;
+    }
+    
+    void Aggro(Unit* pWho) override
+    {
+        if (!m_pInstance)
+            return;
+        
+        // don't attack, if who != player.
+        if (m_creature->GetEntry() == NPC_ELDER_STONEBARK && pWho->GetTypeId() == TYPEID_PLAYER)
+               DoScriptText(SAY_AGGRO_STONE, m_creature);
+               m_uiGroundTremorTimer = urand(10000, 15000);
+               m_uiPetrifiedBarkTimer = urand(2000, 5000);
+               m_uiFistStoneTimer = urand(5000, 7000);
+
+        else if (m_creature->GetEntry() == NPC_ELDER_IRONBRACH && pWho->GetTypeId() == TYPEID_PLAYER)
+               DoScriptText(SAY_AGGRO_IRON, m_creature);
+               m_uiImpaleTimer = urand(7000, 10000);
+               m_uiThornSwarmTimer = urand(15000, 20000);
+               m_uiIronRoorsTimer = urand(10000, 15000);
+               
+        else if (m_creature->GetEntry() == NPC_ELDER_BRIGHTLEAF && pWho->GetTypeId() == TYPEID_PLAYER)
+               DoScriptText(SAY_AGGRO_BRIGHT, m_creature);
+               m_uiSolarFlareTimer = urand(7000, 9000);
+               m_uiUnstableSunBeamTimer = urand(10000, 15000);
+               m_uiBrightleafFluxTimer = 5000;
+    }
+    
+    void KilledUnit(Unit* /*pVictim*/) override
+    {
+        if (!m_pInstance)
+            return;
+        
+        if (m_creature->GetEntry() == NPC_ELDER_STONEBARK)         
+           DoScriptText(urand(0, 1) ? SAY_SLAY_1_STONE : SAY_SLAY_2_STONE, m_creature);
+    
+        else if (m_creature->GetEntry() == NPC_ELDER_IRONBRACH)
+           DoScriptText(urand(0, 1) ? SAY_SLAY_1_IRON : SAY_SLAY_2_IRON, m_creature);
+    
+        else if (m_creature->GetEntry() == NPC_ELDER_BRIGHTLEAF)
+           DoScriptText(urand(0, 1) ? SAY_SLAY_1_BRIGHT : SAY_SLAY_2_BRIGHT, m_creature);
+    }
+    
+    void JustDied(Unit* /*pKiller*/) override
+    {
+        if (!m_pInstance)
+            return;
+        
+        if (m_creature->GetEntry() == NPC_ELDER_STONEBARK)
+           DoScriptText(SAY_DEATH_STONE, m_creature);
+    
+        else if (m_creature->GetEntry() == NPC_ELDER_IRONBRACH)
+           DoScriptText(SAY_DEATH_IRON, m_creature);
+         
+        else if (m_creature->GetEntry() == NPC_ELDER_BRIGHTLEAF)
+           DoScriptText(SAY_DEATH_BRIGHT, m_creature);
+    }
+    
+    void UpdateAI(const uint32 uiDiff) override
+    {
+        if (m_uiGroundTremorTimer < uiDiff)
+        {
+            if (DoCastSpellIfCan(m_creature, m_bIsRegularMode ? SPELL_GROUND_TREMOR_N : SPELL_GROUND_TREMOR_H) == CAST_OK)
+                m_uiGroundTremorTimer = urand(15000, 20000);
+        }
+        else
+            m_uiGroundTremorTimer -= uiDiff;
+        
+        if (m_uiPetrifiedBarkTimer < uiDiff)
+        {
+            if (DoCastSpellIfCan(m_creature, m_bIsRegularMode ? SPELL_PETRIFIED_BARK_N : SPELL_PETRIFIED_BARK_H) == CAST_OK)
+                m_uiPetrifiedBarkTimer = urand(40000, 50000);
+        }
+        else
+            m_uiPetrifiedBarkTimer -= uiDiff;
+        
+        if (m_uiFistStoneTimer < uiDiff)
+        {
+            if (DoCastSpellIfCan(m_creature, SPELL_FISTS_OF_STONE) == CAST_OK)
+                m_uiFistStoneTimer = urand(20000, 30000);
+        }
+        else
+            m_uiFistStoneTimer -= uiDiff;
+        
+        if (m_uiImpaleTimer < uiDiff)
+        {
+            if (DoCastSpellIfCan(m_creature, m_bIsRegularMode ? SPELL_IMPALE_N : SPELL_IMPALE_H) == CAST_OK)
+                m_uiImpaleTimer = urand(12000, 15000);
+        }
+        else
+            m_uiImpaleTimer -= uiDiff;
+        
+        if (m_uiThornSwarmTimer < uiDiff)
+        {
+            if (DoCastSpellIfCan(m_creature, m_bIsRegularMode ? SPELL_THORN_SWARM_N : SPELL_THORN_SWARM_H) == CAST_OK)
+                m_uiThornSwarmTimer = 30000;
+        }
+        else
+            m_uiThornSwarmTimer -= uiDiff;
+        
+        if (m_uiIronRoorsTimer < uiDiff)
+        {
+            if (DoCastSpellIfCan(m_creature, m_bIsRegularMode ? SPELL_IRON_ROOTS_N : SPELL_IRON_ROOTS_H) == CAST_OK)
+                m_uiIronRoorsTimer = urand(20000, 30000);
+        }
+        else
+            m_uiIronRoorsTimer -= uiDiff;
+        
+        if (m_uiSolarFlareTimer < uiDiff)
+        {
+            if (DoCastSpellIfCan(m_creature, m_bIsRegularMode ? SPELL_SOLAR_FLARE_N : SPELL_SOLAR_FLARE_H) == CAST_OK)
+                m_uiSolarFlareTimer = urand(12000, 15000);
+        }
+        else
+            m_uiSolarFlareTimer -= uiDiff;
+        
+        if (m_uiUnstableSunBeamTimer < uiDiff)
+        {
+            if (DoCastSpellIfCan(m_creature, m_bIsRegularMode ? SPELL_UNSTABLE_SUN_BEAM_N : SPELL_UNSTABLE_SUN_BEAM_H) == CAST_OK)
+                m_uiUnstableSunBeamTimer = urand(25000, 30000);
+        }
+        else
+            m_uiUnstableSunBeamTimer -= uiDiff;
+        
+        if (m_uiBrightleafFluxTimer < uiDiff)
+        {
+            if (DoCastSpellIfCan(m_creature, SPELL_BRIGHTLEAF_FLUX) == CAST_OK)
+                m_uiBrightleafFluxTimer = 5000;
+        }
+        else
+            m_uiBrightleafFluxTimer -= uiDiff;
+    }
+};
+    
+CreatureAI* GetAI_boss_freya_elders(Creature* pCreature)
+{
+    return new boss_freya_eldersAI(pCreature);
+}
+
 void AddSC_boss_freya()
 {
     Script* pNewScript;
@@ -1052,4 +1254,10 @@ void AddSC_boss_freya()
     pNewScript->Name = "npc_healthy_spore";
     pNewScript->GetAI = GetAI_npc_healthy_spore;
     pNewScript->RegisterSelf();
-}
+    
+    pNewScript = new Script;
+    pNewScript->Name = "boss_freya_elders";
+    pNewScript->GetAI = GetAI_boss_freya_elders;
+    pNewScript->RegisterSelf();
+    
+}
\ No newline at end of file
diff --git a/sql/mangos_scriptname_full.sql b/sql/mangos_scriptname_full.sql
index 4fbce35..7c4482d 100644
--- a/sql/mangos_scriptname_full.sql
+++ b/sql/mangos_scriptname_full.sql
@@ -1406,6 +1406,9 @@ UPDATE creature_template SET ScriptName='npc_healthy_spore' WHERE entry=33215;
 UPDATE creature_template SET ScriptName='npc_water_spirit' WHERE entry=33202;
 UPDATE creature_template SET ScriptName='npc_snaplasher' WHERE entry=32916;
 UPDATE creature_template SET ScriptName='npc_storm_lasher' WHERE entry=32919;
+UPDATE creature_template SET ScriptName='boss_freya_elders' WHERE entry=32914;
+UPDATE creature_template SET ScriptName='boss_freya_elders' WHERE entry=32915;
+UPDATE creature_template SET ScriptName='boss_freya_elders' WHERE entry=32913;
 UPDATE creature_template SET ScriptName='boss_mimiron' WHERE entry=33350;
 UPDATE creature_template SET ScriptName='boss_leviathan_mk2' WHERE entry=33432;
 UPDATE creature_template SET ScriptName='boss_vx001' WHERE entry=33651;
diff --git a/sql/updates/r3154_mangos.sql b/sql/updates/r3154_mangos.sql
new file mode 100644
index 0000000..dee61c8
--- /dev/null
+++ b/sql/updates/r3154_mangos.sql
@@ -0,0 +1,3 @@
+UPDATE creature_template SET ScriptName='boss_freya_elders' WHERE entry=32914;
+UPDATE creature_template SET ScriptName='boss_freya_elders' WHERE entry=32915;
+UPDATE creature_template SET ScriptName='boss_freya_elders' WHERE entry=32913;
```

**Comment by ghost** [comment] 2015-09-28 22:47
@Tauriella try this patch.

**Comment by xfurry** [comment] 2015-10-04 20:53
Or maybe this one:

``` diff
diff --git a/src/game/SpellMgr.cpp b/src/game/SpellMgr.cpp
index c5b58bf..5bb6e33 100644
--- a/src/game/SpellMgr.cpp
+++ b/src/game/SpellMgr.cpp
@@ -756,7 +756,13 @@ bool IsPositiveEffect(SpellEntry const* spellproto, SpellEffectIndex effIndex)
                         case 27202:
                         case 27203:
                         case 47669:
+                        case 62483:                         // Stonebark's Essence Channel
+                        case 62484:                         // Ironbranch's Essence Channel
+                        case 62485:                         // Brightleaf's Essence Channel
                         case 64996:                         // Reorigination
+                        case 65587:                         // Brightleaf's Essence Channel (h)
+                        case 65588:                         // Ironbranch's Essence Channel (h)
+                        case 65589:                         // Stonebark's Essence Channel (h)
                             return true;
                         default:
                             break;

```

**Comment by Tauriella** [comment] 2015-10-04 21:43
I have your possible fix tested but the same as before
Don't works

**Comment by ghost** [comment] 2015-10-07 04:23
@Tauriella and @Xfurry - I'll use following action:

``` SQL
insert ignore into `creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) values
('3291409','32914','11','0','100','6','0','0','0','0','52','1','0','0','0','0','0','0','0','0','0','0','Elder Stonebark - Disable Aggro Action on Spawn.');
insert ignore into `creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) values
('3291410','32914','10','0','100','7','0','30','5000','5000','52','0','0','0','0','0','0','0','0','0','0','0','Elder Stonebark - Enable Aggro Action on OOC Los 30 yards.');
insert ignore into `creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) values
('3291411','32914','21','0','100','6','0','0','0','0','52','1','0','0','0','0','0','0','0','0','0','0','Elder Stonebark - Disable Aggro Action on Reached Home.');
```

https://github.com/Ulduar/mangos-cata/commit/413eb589b9042959e67eb74dd6edc219d2be25c7
ACTION_T_CONTROL_AGGRO
If true = npc cannot run EVENT_T_AGGRO, if false - can. Tested in game.
On Aggro and Reached Home - Don't use Aggro Action, On OOC_LOS - enable and can yell and other.
![wowscrnshot_100615_232353](https://cloud.githubusercontent.com/assets/12860716/10329041/5c2ce2ea-6cdd-11e5-8c3d-80491574abcb.jpg)
![wowscrnshot_100615_232412](https://cloud.githubusercontent.com/assets/12860716/10329047/7c7c0bac-6cdd-11e5-8a34-2d150a635fc1.jpg)

**Comment by Tauriella** [comment] 2015-10-07 13:38
Hi 
Works this fix ? 
If it so i tested on my Server

**Comment by ghost** [comment] 2015-10-07 14:55
ACTION_T_CONTROL_AGGRO fix aggro yell. Tested in game.
On Spawn- set boolean on true.
On OOC_LOS 30 yards - set boolean on false.
On Reached Home - set boolean on true.
P.S: Cmangos-Wotlk not have ACTION_T_CONTROL_AGGRO. If you add in you core - you can test.
Link higher post
Or you can test my patch in post three. SD2 patch.

**Comment by Tauriella** [comment] 2015-10-08 04:39
Thanks
I check your SD2 Script this Weekend i am im mom a Little busy in my real live

**Comment by Ulduar** [comment] 2015-10-08 14:29
Well, actually decide - which option suits you more. SD2 patch - in it plus the fact that there is a check in the aggro for the player, ie if pWho! = TYPEID_PLAYER - there is a return. EAI - he works too, but you do not have to approach Stonebark.
@Xfurry - thanks for you patch, but he is not solve problem, Kalec arcane bolt also - if add in core positive effect for Arcane Bolt (https://github.com/cmangos/mangos-wotlk/pull/147/files)

**Comment by xfurry** [comment] 2015-10-12 22:26
I need to understand why is this happening.
I think there is some target or aura problem that needs to be fixed in a generic way, not only specific to Freya.

My previous patch doesn't work, so I need to dig a little deeper.

**Comment by Ulduar** [comment] 2015-10-12 22:38
Decide themselves I have solved the problem. My solution working.

**Comment by ghost** [comment] 2015-10-23 15:39
@Tauriella I understand my patch SD2 you are not tested? If not - then do not bother - it is useless.
Not working.
@xfurry https://github.com/cmangos/mangos-cata/blob/b6d14dbc3a0c7f8d42f768faf42ad7291a63df12/src/game/SpellAuraDefines.h#L40
AFLAG_NEGATIVE
The answer to your question. Hack in SpellMgr to change positive effect is not working.
My EAI solution working fine!
![wowscrnshot_102615_184008](https://cloud.githubusercontent.com/assets/12860716/10733484/3cc01f2a-7c29-11e5-9361-0ffbc4b8487f.jpg)

**Comment by xfurry** [comment] 2015-10-28 23:17
@Ulduar your code only fixes the result, and not the root cause. Actually this is not only about the text. It's also about the auras that are cast during the encounter.

The problem can be found here: https://github.com/cmangos/mangos-wotlk/blob/master/src/game/Spell.cpp#L1307

This means that whenever a friendly target is in combat, the unit that cast the spell on the target will also get in combat.
This is the reason why healers get in combat when healing another player that is already in combat.
Fixing this is easy in theory, but really difficult to implement...
The idea is that the elders should be stunned right after starting the combat. This means that they shouldn't be able to cast any spell, hence they shouldn't enter combat with anyone.

**Comment by ghost** [comment] 2015-10-28 23:36
I know about it, more will give you another example - Trial Crusaders Healers - their healing poses a threat to their well - healed friendly targets begin to attack them after receive heal.
Freya's case can fix the result, about the root cause no one thought. My code - a temporary solution. To avoid unnerving.

**Closed** 2015-10-29 21:54 UTC

**Comment by Tauriella** [comment] 2015-10-31 16:45
OMG It's works great
Thank you so much :+1:
